### ISSUE TITLE
WHat should i provide for vendor code and Appkey

### ISSUE THREAD

**Issue by ash21213** [Shoonya-Dev/ShoonyaApi-AmiBroker#1]

**Comment by kpbird** [comment]
send email to api support team. they will provide you all the details

**Comment by Shoonya-Dev** [comment]
Hi,

Shoonya API is now available!

With the help of trading APIs, you can create different automated strategies and have rule-based trading. You can generate API keys from the "Get API Keys" section on the Shoonya "Developer Api Documentation page". 

As always, Shoonya Developer APIs provide all trading APIs completely free of cost.

Following Steps are needed to be followed for API key generation: -

1. Log in to your PRISM portal.

[https://prism.finvasia.com/]

2. Go the the profile on top right. Click on “API Key” 

3. Generate an API key

4. Copy and paste the API key to your software.

VC code is :- Client Code_U **(For Ex. FA12345_U)**

IMEI:- abc1234

How to generate API key from Prism
[https://youtu.be/YbD-NDKGm-I]

To know more: [https://finvasia.com/shoonya-api]
Here is the FAQ: [https://finvasia.com/faqs/apis]

For any queries, feel free to reach us at [apisupport@finvasia.in ](url)
