### ISSUE TITLE
Need help configuring the dll in amibroker. Plugin not showing up in Database settings window

### ISSUE THREAD

**Issue by CodeTrend** [Shoonya-Dev/ShoonyaApi-AmiBroker#2]
Hi,

I have pasted the dlls in the plugin folder
![image](https://user-images.githubusercontent.com/7464558/149176410-e0a0a80b-40c4-447d-9392-04c5f210952a.png)

In database setting this is not showing the new plugin is not showing up
![image](https://user-images.githubusercontent.com/7464558/149176523-a13e4321-b44e-4ebb-b4a9-390bcec4eb7f.png)

Appreciate your help

**Comment by Shoonya-Dev** [comment]
Greetings from FINVASIA!

Thanks for your Concern.

For Quoted Query, Please feel free to reach us, email at apisupport@finvasia.in or call at 0172-4740000
& also Just visit our website there is a Live chat option.
