### ISSUE TITLE
32 bit ShoonyaApi.dll does not work

### ISSUE THREAD

**Issue by Josh1-rtd** [Shoonya-Dev/ShoonyaApi-AmiBroker#5]
Amibroker gives error message - The following plugins ShoonyApi.dll   are 64 bit and as such cannot be loaded into 32 bit version of Amibroker you are running now

**Comment by Shoonya-Dev** [comment]
Greetings from Shoonya!

Thanks for your Concern.

If you are running a 32-bit AMI Broker in a 64-bit operating system then you have to install a 32-bit Shoony plugin & If you are running 64 bit AMI Broker in a 64-bit operating system then you have to install a 64-bit Shoonya Plugin.

**Comment by Josh1-rtd** [comment]
I know that very well. I am using 32-bit Amibroker and installed 32-bit Shoonya plugin. it does not work. Kindly re-examine what you uploaded here.
