### ISSUE TITLE
32 bit plugin does not work

### ISSUE THREAD

**Issue by Josh1-rtd** [Shoonya-Dev/ShoonyaApi-AmiBroker#6]
I am using 32-bit Amibroker and installed 32-bit Shoonya plugin. it does not work. Kindly re-examine what you uploaded here. Amibroker gives error message - The following plugins ShoonyApi.dll are 64 bit and as such cannot be loaded into 32 bit version of Amibroker you are running now.
Please do not give standard reply. I know programming

**Comment by Shoonya-Dev** [comment]
Greetings from Shoonya!

Thanks for your concern.

Its Working fine, We request please share your issue at **apisupport@shoonya.com** 
The team will be contacting you.

Team Shoonya
