### ISSUE TITLE
Plugin Status not visible in Amibroker.

### ISSUE THREAD

**Issue by Josh1-rtd** [Shoonya-Dev/ShoonyaApi-AmiBroker#7]
I have downloaded 32bit plugin again and this time Amibroker did not complain. However, Plugin status does not appear in Amibroker. Therefore it is difficult to confirm whether it is connected or not.

**Comment by Shoonya-Dev** [comment]
Greetings from Shoonya!

You need to setup the plugin as per your Amibroker configuration, or you can refer to the below-attached link:

https://www.youtube.com/watch?v=TXApp6GUDSQ&t=248s
